USE [master]
GO
/****** Object:  Database [ProyectoPW]    Script Date: 09/11/2022 11:58:37 a. m. ******/
CREATE DATABASE [ProyectoPW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProyectoPW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ProyectoPW.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProyectoPW_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ProyectoPW_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ProyectoPW] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProyectoPW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ProyectoPW] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ProyectoPW] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ProyectoPW] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ProyectoPW] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ProyectoPW] SET ARITHABORT OFF 
GO
ALTER DATABASE [ProyectoPW] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ProyectoPW] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ProyectoPW] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ProyectoPW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ProyectoPW] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ProyectoPW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ProyectoPW] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ProyectoPW] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ProyectoPW] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ProyectoPW] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ProyectoPW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ProyectoPW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ProyectoPW] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ProyectoPW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ProyectoPW] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ProyectoPW] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ProyectoPW] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ProyectoPW] SET RECOVERY FULL 
GO
ALTER DATABASE [ProyectoPW] SET  MULTI_USER 
GO
ALTER DATABASE [ProyectoPW] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ProyectoPW] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ProyectoPW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ProyectoPW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ProyectoPW] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ProyectoPW] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ProyectoPW', N'ON'
GO
ALTER DATABASE [ProyectoPW] SET QUERY_STORE = OFF
GO
USE [ProyectoPW]
GO
/****** Object:  Table [dbo].[Comentario]    Script Date: 09/11/2022 11:58:37 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comentario](
	[ID_Comentario] [int] NOT NULL,
	[ID_Usuario] [int] NOT NULL,
	[Contenido] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Comentario] PRIMARY KEY CLUSTERED 
(
	[ID_Comentario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Habitacion]    Script Date: 09/11/2022 11:58:37 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Habitacion](
	[ID_Habitacion] [int] NOT NULL,
	[ID_HOTEL] [int] NOT NULL,
	[Num_Habitacion] [tinyint] NOT NULL,
 CONSTRAINT [PK_Habitacion] PRIMARY KEY CLUSTERED 
(
	[ID_Habitacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOTEL]    Script Date: 09/11/2022 11:58:37 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOTEL](
	[ID_HOTEL] [int] NOT NULL,
	[NOMBRE_HOTEL] [varchar](20) NOT NULL,
	[Direccion] [varchar](50) NOT NULL,
	[Habitaciones] [tinyint] NULL,
 CONSTRAINT [PK_HOTEL] PRIMARY KEY CLUSTERED 
(
	[ID_HOTEL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pago]    Script Date: 09/11/2022 11:58:37 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pago](
	[ID_Pago] [int] NOT NULL,
	[ID_Hotel] [int] NOT NULL,
	[Pago] [money] NOT NULL,
	[ID_Reservacion] [int] NOT NULL,
	[Tipo_Pago] [varchar](30) NOT NULL,
 CONSTRAINT [PK_Pago] PRIMARY KEY CLUSTERED 
(
	[ID_Pago] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reservacion]    Script Date: 09/11/2022 11:58:37 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reservacion](
	[ID_Reservacion] [int] NOT NULL,
	[ID_Habitacion] [int] NOT NULL,
	[ID_Usuario] [int] NOT NULL,
	[ID_Hotel] [int] NOT NULL,
 CONSTRAINT [PK_Reservacion] PRIMARY KEY CLUSTERED 
(
	[ID_Reservacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 09/11/2022 11:58:37 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[ID_Usuario] [int] NOT NULL,
	[Nombre] [varchar](20) NOT NULL,
	[Apellido] [varchar](20) NOT NULL,
	[Direccion] [varchar](50) NULL,
	[Fecha_Nacimient] [datetime] NULL,
	[Correo_Electr] [varchar](20) NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[ID_Usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Comentario]  WITH CHECK ADD  CONSTRAINT [FK_Comentario_Usuario] FOREIGN KEY([ID_Usuario])
REFERENCES [dbo].[Usuario] ([ID_Usuario])
GO
ALTER TABLE [dbo].[Comentario] CHECK CONSTRAINT [FK_Comentario_Usuario]
GO
ALTER TABLE [dbo].[Habitacion]  WITH CHECK ADD  CONSTRAINT [FK_Habitacion_Habitacion] FOREIGN KEY([ID_HOTEL])
REFERENCES [dbo].[HOTEL] ([ID_HOTEL])
GO
ALTER TABLE [dbo].[Habitacion] CHECK CONSTRAINT [FK_Habitacion_Habitacion]
GO
ALTER TABLE [dbo].[Habitacion]  WITH CHECK ADD  CONSTRAINT [FK_Habitacion_HOTEL] FOREIGN KEY([ID_HOTEL])
REFERENCES [dbo].[HOTEL] ([ID_HOTEL])
GO
ALTER TABLE [dbo].[Habitacion] CHECK CONSTRAINT [FK_Habitacion_HOTEL]
GO
ALTER TABLE [dbo].[Pago]  WITH CHECK ADD  CONSTRAINT [FK_Pago_HOTEL] FOREIGN KEY([ID_Hotel])
REFERENCES [dbo].[HOTEL] ([ID_HOTEL])
GO
ALTER TABLE [dbo].[Pago] CHECK CONSTRAINT [FK_Pago_HOTEL]
GO
ALTER TABLE [dbo].[Pago]  WITH CHECK ADD  CONSTRAINT [FK_Pago_Reservacion] FOREIGN KEY([ID_Reservacion])
REFERENCES [dbo].[Reservacion] ([ID_Reservacion])
GO
ALTER TABLE [dbo].[Pago] CHECK CONSTRAINT [FK_Pago_Reservacion]
GO
ALTER TABLE [dbo].[Reservacion]  WITH CHECK ADD  CONSTRAINT [FK_Reservacion_Habitacion] FOREIGN KEY([ID_Habitacion])
REFERENCES [dbo].[Habitacion] ([ID_Habitacion])
GO
ALTER TABLE [dbo].[Reservacion] CHECK CONSTRAINT [FK_Reservacion_Habitacion]
GO
ALTER TABLE [dbo].[Reservacion]  WITH CHECK ADD  CONSTRAINT [FK_Reservacion_HOTEL] FOREIGN KEY([ID_Hotel])
REFERENCES [dbo].[HOTEL] ([ID_HOTEL])
GO
ALTER TABLE [dbo].[Reservacion] CHECK CONSTRAINT [FK_Reservacion_HOTEL]
GO
ALTER TABLE [dbo].[Reservacion]  WITH CHECK ADD  CONSTRAINT [FK_Reservacion_Usuario] FOREIGN KEY([ID_Usuario])
REFERENCES [dbo].[Usuario] ([ID_Usuario])
GO
ALTER TABLE [dbo].[Reservacion] CHECK CONSTRAINT [FK_Reservacion_Usuario]
GO
USE [master]
GO
ALTER DATABASE [ProyectoPW] SET  READ_WRITE 
GO
